-- MySQL Script generated by MySQL Workbench
-- Fri Feb 19 14:40:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webcapstone
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `webcapstone` ;

-- -----------------------------------------------------
-- Schema webcapstone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webcapstone` DEFAULT CHARACTER SET utf8 ;
USE `webcapstone` ;

-- -----------------------------------------------------
-- Table `webcapstone`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcapstone`.`users` ;

CREATE TABLE IF NOT EXISTS `webcapstone`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `type` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `card_no` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcapstone`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcapstone`.`products` ;

CREATE TABLE IF NOT EXISTS `webcapstone`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NULL,
  `description` VARCHAR(300) NULL,
  `quantity` INT NULL,
  `released_date` DATE NULL,
  `expiry_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcapstone`.`lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcapstone`.`lessons` ;

CREATE TABLE IF NOT EXISTS `webcapstone`.`lessons` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(300) NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcapstone`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcapstone`.`orders` ;

CREATE TABLE IF NOT EXISTS `webcapstone`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATE NULL,
  `total_price` DOUBLE NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcapstone`.`orders_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcapstone`.`orders_details` ;

CREATE TABLE IF NOT EXISTS `webcapstone`.`orders_details` (
  `orders_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `description` VARCHAR(100) NULL,
  `quoted_price` DOUBLE NULL,
  PRIMARY KEY (`orders_id`, `products_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcapstone`.`tutorials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcapstone`.`tutorials` ;

CREATE TABLE IF NOT EXISTS `webcapstone`.`tutorials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL,
  `url` VARCHAR(100) NULL,
  `description` VARCHAR(150) NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcapstone`.`tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcapstone`.`tests` ;

CREATE TABLE IF NOT EXISTS `webcapstone`.`tests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webcapstone`.`users_progress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webcapstone`.`users_progress` ;

CREATE TABLE IF NOT EXISTS `webcapstone`.`users_progress` (
  `users_id` INT NOT NULL,
  `tests_id` INT NOT NULL,
  `score` INT NULL,
  `detail` VARCHAR(50) NULL,
  PRIMARY KEY (`users_id`, `tests_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
